### ISSUE TITLE
bug: no output on failing duty when run on Windows

### ISSUE THREAD

**Issue by blairconrad** [pawamoy/duty#23] opened 2024-10-15 15:02 UTC
### Description of the bug
When I create a failing "duty" and run it, no output is displayed

### To Reproduce

```
git clone https://github.com/blairconrad/duty-bug
cd duty-bug
uv run duty test
```

On Windows, with a failing "duty", run the duty.

### Full traceback
No exception or traceback. No output at all, in fact, except a non-zero exit code.
See more at https://github.com/blairconrad/duty-bug/blob/c3f03f4ebf5e0fdc15d6e4b7b14b450239c1615c/README.md (which includes screenshots that you didn't want).

Adding the `--capture=none` causes the output to be displayed.

### Expected behavior
When the duty fails, I expected the output from the command to be displayed in the console.

### Environment information

- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.13.0 (E:\Dev\duty-bug\.venv\Scripts\python.exe)
- __Environment variables__:
- __Installed packages__:
  - `duty` v1.4.2

### Additional context

![no output](https://github.com/blairconrad/duty-bug/blob/c3f03f4ebf5e0fdc15d6e4b7b14b450239c1615c/images/duty-shows-no-failures.png?raw=true)

Whether I add `--capture=none` to the command or not, the error code from a duty using `pytest` is 1. For `ruff`, the error code is 120 normally or 1 with `--capture=none`.

**Comment by blairconrad** [comment] 2024-10-15 15:03
Hi. I am otherwise excited by the library, and was keen to try it out as an `invoke` replacement.
Thanks for your time.

**Comment by pawamoy** [comment] 2024-10-15 16:53
Hi @blairconrad, thank you for the report! Sorry for the wording about screenshots in the issue template, too many times I get a screenshot of the traceback instead of the text, which is unusable :sweat_smile: 

So, that's weird. I don't have a machine with the annoying operating system installed (that's how I call it :speak_no_evil:) so I won't be able to investigate, unfortunately. I suppose something goes wrong when trying to capture the output of the command, and that also impacts the exit code?

I should try to fix [the single test not passing on this system](https://github.com/pawamoy/duty/actions/runs/10791369777/job/29928633346), to see how it goes with higher Python versions. Let me try to do that.

**Comment by blairconrad** [comment] 2024-10-15 17:37
> too many times I get a screenshot of the traceback instead of the text, which is unusable

Oh, I understand. It's the worst!

Ah, I was a bit surprised since it seemed like part of the motivation for writing duty was an annoying bit of (lack of?) support invoke had for some Windows scenario. I must've read wrong. Thanks for looking. I can also take a peek, but would probably need some guidance.

For What it's worth, the behaviour is the same down to Python 3.8.

**Comment by blairconrad** [comment] 2024-10-15 17:59
> And some of them don't have a choice to use Windows 

it me

**Comment by pawamoy** [comment] 2024-10-15 19:32
> I can also take a peek, but would probably need some guidance.

Are you familiar with debuggers? VSCode's one is quite easy to use IMO. I'd suggest putting a break point at this line:

https://github.com/pawamoy/duty/blob/de4cc5b865e7e719ddb5ee7edd21e0637d963b67/src/duty/context.py#L83

...and see if anything weird is happening. Check if the output is ever captured lower in the stack, and if it's "lost" at some point?

**Comment by pawamoy** [comment] 2024-10-15 19:37
https://stackoverflow.com/a/74273563/3451029

> Changed in version 3.6: If an error occurs in the cleanup after the Python interpreter has caught SystemExit (such as an error flushing buffered data in the standard streams), the exit status is changed to 120.

**Comment by blairconrad** [comment] 2024-10-15 22:49
I am familiar with debuggers but haven't debugged _python_ for probably 20 years. 'pdb' I think?
 I've a mind like a sieve.
Still, I'm game to try. And I've used VS Code to debug. Busy week, so you may not hear from me for a few days. Then again, so far I'm the only one complaining, so I guess no rush...

**Comment by pawamoy** [comment] 2024-10-15 23:20
Thanks, that'd be great, and yeah, no rush. I might try stealing some friends laptop when I get the chance to, to debug myself. Will let you know.

**Comment by pawamoy** [comment] 2024-10-17 14:55
Just updated failprint (boilerplate), and ran tests again in CI, it looks like everything is passing on Windows: https://github.com/pawamoy/failprint/actions/runs/11387501049/job/31682269574. So in theory it should work in duty too :shrug:

**Comment by blairconrad** [comment] 2024-10-18 10:55
I had a few minutes to debug last night and traced through to the point where `failprint.run` was called. I took a peak at that method and saw a switch for [`cmd` as a callable or not](https://github.com/pawamoy/failprint/blob/b1f27df8e9105349cc421b3cfd2a0477d766b160/src/failprint/runners.py#L99-L102) and figured that might be the difference; I'd been using the `pytest` callable.

I haven't dived further into the code, but I wrote 2 duties:

```python
@duty
def pytest_inline(ctx: Context) -> None:
    ctx.run(tools.pytest())

@duty
def pytest_exe(ctx: Context) -> None:
    ctx.run("pytest.exe")
```

and ran them:

```
 λ  uv run --with duty duty pytest_inline # exit code 1, no other result printed
 λ  uv run --with duty duty pytest_exe    # exit code 1, and look at the output 
✗ pytest.exe (1)
  ============================= test session starts =============================
  platform win32 -- Python 3.10.15, pytest-8.3.3, pluggy-1.5.0
  rootdir: C:\Dev\dicognito
  configfile: pyproject.toml
  collected 325 items
  ...
```

So I think my next step will be to look harder at failprint.

**Comment by pawamoy** [comment] 2024-10-18 11:16
Thanks, that'salready helpful. It means subprocess output capture works, but file descriptor capture doesn't (`tools` run in the same process, for example calling pytest's CLI entry point directly).

That's what I suspected, but from looking at failprint's test suite, it looks like this is covered (file descriptor capture is used in tests that pass on windows). Maybe just some edge case.

**Comment by blairconrad** [comment] 2024-10-19 01:29
Fun fact! Many failprint tests fail for me when run from powershell. I see your GitHub actions run within git bash (or at least some do; I didn't check all). It's a valid use case, but I'd say probably not comprehensive. But I'm sort of off topic now.

I ran the failprint tests under git bash locally and they passed. So I went back to my test repo above and...  `uv run --with duty duty pytest_inline` still behaves badly. No output. So there goes that theory.

I haven't yet dug into the individual failprint tests that apply. Will in the next week, I expect.

Also, if I'm yammering too much, tell me to shut up. I will not be offended.

**Comment by pawamoy** [comment] 2024-10-19 10:53
> Fun fact! Many failprint tests fail for me when run from powershell.

Ha, interesting! Yeah supporting Windows is already boring so I kinda expect users to use WSL2 or at least Bash ports (like the one installed alongside Git-for-Windows). But I'm not against better supporting Powershell! I just won't be the one doing the work :smile: If you want to keep investigating and send PRs, please do, I'll follow along and review :slightly_smiling_face:

Just learned "yammering" today, keep yammering please! :heart:

**Comment by blairconrad** [comment] 2024-10-21 11:05
I have only small chunks of time to work on this, so continue to make notes here, partly to boost my memory and partly in case it's of interest.

One things that has occurred to me, @pawamoy: this now appears to be a failprint bug. Do you want me to create a new issue there (or do you want to move this one) or should we keep working here?

Regardless, when debugging this quite naive file

```python
import sys
import failprint

def succeed() -> int:
    print("succeeded")
    return 0

def main() -> None:
    capture = failprint.Capture.BOTH
    if len(sys.argv) > 1:
        capture = failprint.Capture(sys.argv[1])
    failprint.run(succeed, capture=capture)

if __name__ == "__main__":
    main()
```

(run as `uv run run_passing_callable.py`), I see a failure at `print("succeeded")`:

```
[WinError 6] The handle is invalid
  File "C:\Dev\failprint\src\failprint\runners.py", line 216, in run_function_get_code
    result = func(*args, **kwargs)
  File "C:\Dev\failprint\run_passing_callable.py", line 5, in succeed
    print("succeeded")
    ~~~~~^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

  File "C:\Dev\failprint\src\failprint\runners.py", line 225, in run_function_get_code
    sys.stderr.write(traceback.format_exc() + "\n")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\failprint\src\failprint\runners.py", line 194, in run_function
    code = run_function_get_code(func, args=args, kwargs=kwargs)
  File "C:\Dev\failprint\src\failprint\runners.py", line 100, in run
    code, output = run_function(cmd, args=args, kwargs=kwargs, capture=capture, stdin=stdin)
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\failprint\run_passing_callable.py", line 12, in main
    failprint.run(succeed, capture=capture)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\failprint\run_passing_callable.py", line 15, in <module>
    main()
    ~~~~^^
  File "C:\Users\blair\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\blair\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\runpy.py", line 198, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
OSError: [WinError 6] The handle is invalid
```

two `OSError` due to an invalid output handle; the first because `sys.stdout` is invalid (at `print("succeeded")` and the second when handling that error in `runners.py` via 
```python
    except Exception:  # noqa: BLE001
        sys.stderr.write(traceback.format_exc() + "\n")
        return 1
```

running with `capture` set to none avoids this problem.

`sys.stdout` is a `_io.TextIOWrapper` with an `_io._WindowsConsoleIO mode='wb' closefd=False` buffer. It is not closed. I don't know how to copy multiple lines out of the debugger view, so here's a screenshot:

![image](https://github.com/user-attachments/assets/43bbd219-8d55-4834-8cdc-bd4ccd76a602)

more later

**Comment by pawamoy** [comment] 2024-10-21 11:17
Great info, thanks. Could you try setting the env var mentioned in this SO answer and try again? https://stackoverflow.com/a/52377087/3451029

**Comment by blairconrad** [comment] 2024-10-22 01:06
Better!

In that it failed more obviously.

```powershell
λ  $env:PYTHONLEGACYWINDOWSSTDIO='true'
λ  uv run .\run_failing_callable.py both
Traceback (most recent call last):
  File "C:\Dev\failprint\run_failing_callable.py", line 15, in <module>
    main()
    ~~~~^^
  File "C:\Dev\failprint\run_failing_callable.py", line 12, in main
    failprint.run(fail, capture=capture)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\failprint\src\failprint\runners.py", line 120, in run
    print(unescape(parse(rendered)))  # noqa: T201
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blair\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2717' in position 5: character maps to <undefined>
```

But seriously, seems to be an improvement. I don't think there was a failure with the stream, just encoding your very fancy failure character. If I replace `\u2271` with `X` in the template, I see

```powershell
λ  uv run .\run_failing_callable.py both
X fail() (1)
  failed
```

(And similarly for a successful run.)

So it looks like the big problem with this approach is the olde-timey codec Python thinks we should use when printing. (And/or the overly ambitious template!)

I got curious and took a peek at what [pytest does](https://github.com/pytest-dev/pytest/blob/26215b8f795a2b13acc1a8827fdfb6a29b502a6a/src/_pytest/capture.py#L82-L134) and tried it, because why not? And I failed miserably with 

```
object address  : 000001C4C41A03A0
object refcount : 3
object type     : 00007FFF3569BE00
object type name: OSError
object repr     : OSError(9, 'The handle is invalid', None, 6, None)
lost sys.stderr
Exception ignored in: <_io.TextIOWrapper name=5 encoding='utf-8'>
```

which surprised and confused me. I've never given consoles, stdout, and friends much thought, so I'm coming in with no knowledge. Innocent me would've expected that you'd just be replacing `sys.stdout` and restoring it at the end, but clearly I don't know anything!
Sorry I have nothing more at this time. I'll try to learn more later. But it looks like this is getting to be more trouble than maybe it's worth!

**Comment by pawamoy** [comment] 2024-10-22 02:03
Or not!

If it's just an encoding issue triggering another issue, maybe we can fix the encoding issue directly.

Try removing the env var you set, and instead set `PYTHONUTF8=1`. If that fails, try adding `PYTHONIOENCODING=UTF8"`. If that fails again, try to make sure most relevant files in your repository or dummy repro are UTF8 encoded.

**Comment by blairconrad** [comment] 2024-10-22 11:07
Ah, I don't think it's the encoding issue triggering another issue. If I remove `$env:PYTHONUTF8`, failprint fails while duplicating the stream, before printing anything. Removing `PYTHONLEGACYWINDOWSSTDIO` and setting `PYTHONUTF8` gives the same lack of output and 120 exit code as before. But if I experiment with combinations of variables:

```powershell
λ  $env:PYTHONLEGACYWINDOWSSTDIO='true'
λ  $env:PYTHONUTF8=1
λ  uv run .\run_failing_callable.py both
Γ£ù fail() (1)
  failed
```

you can see the UTF-8-encoded `✗` is rendered as its 3 constituent bytes. Same result with `PYTHONIOENCODING` set to "UTF8":
```powershell
λ  $env:PYTHONLEGACYWINDOWSSTDIO='true'
λ  rm env:PYTHONUTF8
λ  $env:PYTHONIOENCODING='UTF8'
λ  uv run .\run_failing_callable.py both
Γ£ù fail() (1)
  failed
```

I even tried both PYTHONLEGACYWINDOWSSTDIO and PYTHONIOENCODING. No difference.

My test files were already UTF-8 encoded (or ASCII-encoded, since I have no non-ASCII characters). I did UTF-8 encode `src\failprint\formats.py` as UTF-8, but there was no difference.

**Comment by blairconrad** [comment] 2024-10-22 12:19
I am _not_ trying to get you (or anyone) to rewrite failprint, but to expand on 

> Innocent me would've expected that you'd just be replacing sys.stdout and restoring it at the end

I hacked up

```python
import sys
import time

def main() -> None:
    def failing() -> int:
        print("failed")
        return 1

    def passing() -> int:
        print("passed")
        return 0


    reset = "\x1b[0m"
    red = "\x1b[31m"
    green = "\x1b[32m"

    command = sys.argv[1]

    old_stdout = sys.stdout
    fake_stdout = open("stdout.txt", "w")
    sys.stdout = fake_stdout
    result = 0
    try:
        print(f"running {command}", end="\r", file=old_stdout)
        time.sleep(1)
        result = vars()[command]()
    finally:
        fake_stdout.flush()
        fake_stdout.close()
        sys.stdout = old_stdout
        if result == 0:
            print(f"{green}✓ {command} succeeded{reset}")
        else:
            print(f"{red}✗ {command} failed{reset}")
            print(open("stdout.txt").read())
```

which I'm sure, for various reasons, is terrible.

But:

![image](https://github.com/user-attachments/assets/04330441-bb65-4cbc-ac2a-6cc0aeab472b)

**Comment by pawamoy** [comment] 2024-10-22 12:49
Patching sys.stdout and sys.stderr is indeed the easy thing to do, and what we actually did before. But it's not enough to capture all the ways Python programs can use to write to stdout / stderr. Consider for example a Python function that runs a subprocess. The patched sys.stdout has no effect on the subprocess, so it's output isn't captured and leaks to the outer console.

So we went lower and started capturing things at the file descriptor level, which captures everything. Apparently it doesn't work well with PowerShell. I can do one thing: try detecting PowerShell and set the `PYTHONLEGACYWINDOWSSTDIO` environment variable, since it seems to be improving the situation :)

**Comment by blairconrad** [comment] 2024-10-22 12:58
> Apparently it doesn't work well with PowerShell

It's not powershell, as far as I can tell. I've replicated with plain old cmd.

**Comment by blairconrad** [comment] 2024-10-22 13:56
> Consider for example a Python function that runs a subprocess. The patched sys.stdout has no effect on the subprocess, so its output isn't captured and leaks to the outer console.

Indeed a good point. I had considered a subprocess, and a python callable, but not a callable that launched a process.

**Comment by pawamoy** [comment] 2024-10-22 14:11
> It's not powershell, as far as I can tell. I've replicated with plain old cmd.

Oh OK, so in any Windows shell basically. Bash ports seem to work fine. Maybe we could always set the env var, if that doesn't affect the places where failprint already works.

> A shame, as otherwise just stealing sys.stdout and sys.stderr is very satisfying!

Yep, too bad the annoying operating system is annoying again. Just to confirm (and I'm not saying you're asking for it, which you aren't :+1:), I won't make efforts to support this through options or flags or fallbacks or whatever :relaxed: 

Lets just see how CI behave with `PYTHONLEGACYWINDOWSSTDIO=1`.

**Comment by pawamoy** [comment] 2024-10-22 14:21
Tests still passing: https://github.com/pawamoy/failprint/actions/runs/11462192089/job/31893021304. If you want to send a PR that also runs tests on different shells on Windows, I'll review it.

**Comment by blairconrad** [comment] 2024-10-23 01:10
Hey, @pawamoy. That's excellent. I can certainly make an effort. I tried quickly earlier today and had fights with the workflow. Also even when I hacked things up terribly, the tests passed on GitHub but not locally, so I fear the environment isn't quite how I think it is. I'll pick away at it.

**Comment by blairconrad** [comment] 2024-10-23 01:27
I might as well continue to bother you. I have created a branch to start playing. It's pointing at 65270cfd66fbb15f5d17f347a8bba8f304f9f332, just like yours.
Yet
* [your install dependencies succeeds](https://github.com/pawamoy/failprint/actions/runs/11462315508/job/31893417099)
* and [mine fails with package resolution errors](https://github.com/pawamoy/failprint/actions/runs/11462315508/job/31893417099) (which I can kind of support, to tell the truth)

Have you any idea why this is? It's kind of a bummer. The failprint/duty co-dependency are kinda throwing a wrench in my style here, but super frustrating is not understanding why _your_  actions shoud succeed where my fork's don't. Unless it's the cache. I fear it's the cache. I don't want it to be, but that's all that comes to mind...

**Comment by blairconrad** [comment] 2024-10-23 10:18
Update: search was hard, but I did find https://github.com/astral-sh/uv/issues/8148.

**Comment by pawamoy** [comment] 2024-10-23 10:20
Oh, so sorry I wasn't able to help before. Such errors in CI can be fixed with a simple upgrade from the template that generated the project. Let me do that!

**Comment by blairconrad** [comment] 2024-10-23 10:24
🤦🏻 I'm bad at pasting link. Failing action now linked properly above. Also, I just noticed that there's a "discussion" for this project. Would you rather we be there?

**Comment by pawamoy** [comment] 2024-10-23 10:28
No it's fine, all the context is here already, lets keep the discussion here :slightly_smiling_face: I can cross-link issues from other repos in commits, it's not a problem.

Thanks for the link. So it's the "right" error indeed. Branch `main` should have fixed it. Is your branch up-to-date?

**Comment by pawamoy** [comment] 2024-10-23 10:29
Basically, the solution to this error is to git-fetch all commits and tags in CI.

**Comment by blairconrad** [comment] 2024-10-23 10:30
At the time of that build, my branch was https://github.com/pawamoy/failprint/commit/65270cfd66fbb15f5d17f347a8bba8f304f9f332, same as the build I linked to on the official failprint repo.

**Comment by pawamoy** [comment] 2024-10-23 12:02
Ah, do you actually *have* tags in your fork? Might need to pull them from upstream somehow? I assume `git pull upstream --tags` given you've declared an `upstream` remote.

**Comment by pawamoy** [comment] 2024-10-23 12:06
What you experience might be an argument in favor of `uv` *not* checking the version of the current project (as suggested in the issue you found), as it basically forces contributors to manually pull and push tags to their forks (to be confirmed).

**Comment by pawamoy** [comment] 2024-10-23 12:07
Don't hesitate to open a PR on failprint in draft mode, at least you'll get the upstream CI to run the tests.

**Comment by blairconrad** [comment] 2024-10-23 12:10
> Don't hesitate to open a PR on failprint in draft mode

Will do. Believe it or not, I was avoiding to try to _minimize_ the amount I'd have to annoy you. That backfired!

**Comment by pawamoy** [comment] 2024-10-23 12:13
No worries haha. Sorry for all the troubles :smile:

**Comment by blairconrad** [comment] 2024-10-23 12:25
There's no troubles. I'm having a good time.

I'm not sure if you get notified if I create PR that requires approval to run actions _without having commits beyond ones that have already triggered actions and then add a commit_ or not. And I'm hesitant to mention it, because it seems like I'm impatient, but I'm aware of our time difference and figure I should mention that pawamoy/failprint#20 is sitting there waiting for you to tell it I'm "trustworthy enough to run actions". Sorry. Thanks. Sorry.

**Comment by pawamoy** [comment] 2024-11-26 15:33
Hey, coming back to this. So, I can close the draft PR in failprint right? IIRC all there is to do is document the `PYTHONLEGACYWINDOWSSTDIO=1` (and maybe `PYTHONUTF8=1` and `PYTHONIOENCODING=utf8`) environment variable(s) in both failprint and duty.

**Comment by blairconrad** [comment] 2024-11-26 18:54
Ah, apologies.

I think you're right. The CI environment doesn't allow us to reproduce the bug. My current understanding is that 

* setting `PYTHONLEGACYWINDOWSSTDIO=1` avoids the failure to duplicate the streams
* but we likely now get an error saying
   > <samp>'charmap' codec can't encode character '\u2713' in position 5: character maps to \<undefined\></samp>  
* setting either `PYTHONUTF8=1` or `PYTHONIOENCODING='UTF-8'` avoids this problem, but at the cost of mangled output:
   > <samp>Γ£ô passing()</samp>

So this seems like something that could be documented away, yes. I'd originally thought to submit docs, but life interfered and I forgot about it. :blush:
If you want a submission, I can still do. But sometimes project owners are more particular about documentation, and if you think it's easier on you if you control the docs, no worries.

As a bonus action, I wonder if defining a different default template for when `PYTHONLEGACYWINDOWSSTDIO` is active is reasonable. I was going to say that we're using the cp1252 codepage so picking replacements for ✓ or ✗ from there might help, but I found there's different behaviour when I'm running in normal cmd prompts or Windows Terminal. The former respects the cp1252 values, but the latter prints weird stuff, like ▒  in place of ± (which I encoded as `\xb1`). Still, using something like + and - might get the message across and be portable.

Regardless, I'll close the PR.  Thanks for your time and sorry for letting it languish.

**Comment by blairconrad** [comment] 2024-11-27 11:56
I'm back, briefly. I scanned the docs. failprint has very little docs; not a lot of structure to play with. For duty, I had great hopes for [Capturing commands output](https://pawamoy.github.io/duty/usage/#capturing-commands-output) at first, but then saw that it has a different focus.

Carrying on with all the thoughts that come to my mind:

If you don't like a troubleshooting section there could be an "OS-specific" section (which would have one thing in it again) or even a "Windows" section, I suppose.

Or you could add to the [Running duties](https://pawamoy.github.io/duty/usage/#running-duties) section: "Environment Variables". Mentioning `PYTHONLEGACYWINDOWSSTDIO` in there, with the error behaviour encountered when it's _not_ present, may help.

As far as the "mangled output characters" goes, your note about customizing the output would fit really well in [Formatting duty output](https://pawamoy.github.io/duty/usage/#formatting-duty-output). For whatever my opinion's worth, I think it's a good path.

Thanks for listening. Happy to contribute however you think I can. After I go for a hike. Toodles.

**Comment by pawamoy** [comment] 2024-11-27 13:30
Thanks! I'll send a PR soon and tag you for review :slightly_smiling_face:

**Comment by blairconrad** [comment] 2024-11-28 13:28
Oh, I forgot to say. I tried with various emojis and non-ASCII characters, setting PYTHONIOENCODING to UTF-8 and even UTF-16, and I had no joy. I'm not saying there's nothing that would work for a universal template (heck, I guess using "+" and "-" would work, but may be unsatisfying).

**Comment by blairconrad** [comment] 2024-11-28 15:31
Even in Windows Terminal.

**Comment by pawamoy** [comment] 2024-11-28 16:06
Then it is doomed :man_shrugging:

**Closed** 2024-12-04 00:52 UTC
Labels: docs
